# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.16-buster AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY /bot ./bot
COPY /scrape ./scrape
COPY . ./

RUN go build -o /streamer-bot

##
## Deploy
##
FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build streamer-bot streamer-bot
COPY bot.agent /
COPY streamer-data.html /

USER nonroot:nonroot

ENTRYPOINT ["/streamer-bot"]